Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 12
    vb.memory = "8184"
  end

  config.vm.hostname = "tsiguenzS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.provision "shell", path: "scripts/server_init.sh"

end
