Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

  config.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime", run: "always"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade
    apt-get install -y  zsh curl git vagrant vim 
    chsh -s /bin/zsh vagrant
    su vagrant -c 'sh -c \
    "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  SHELL
  # config.vm.define "tmatisS" do |tmatisS|
  #  config.vm.box = "generic/debian9"
  #end

  #config.vm.define "tsiguenzSW" do |tsiguenzSW|
  #  config.vm.box = "debian/bullseye64"
  #end
end
