Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 1
    vb.memory = "1024"
  end

  config.vm.define "tsiguenzS" do |server|
    server.vm.hostname = "tsiguenzS"
    server.vm.network "private_network", ip: "192.168.56.110"
  end

  config.vm.define "tsiguenzSW" do |worker|
    worker.vm.hostname = "tsiguenzSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
  end
end
